version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      build-and-test-tooling:
        patterns:
          - "*"
    open-pull-requests-limit: 5
